import{g as m,j as h,S as _,q as o,T as i,c as f,a as g,o as y}from"./CzqWsblW.js";import{u as S}from"./ZkQ_l8FP.js";const w={class:"container py-5 text-center"},T={__name:"auth-redirect",async setup(b){var c;let e,t;const u=h(),p=m(),l=S(),n=u.query.code;if(n){const s=_(),a=`${s.public.baseUrl.replace(/\/$/,"")}${s.public.oauth.redirectPath}`;try{const{token:r,username:d}=([e,t]=o(()=>$fetch(s.public.apiBase+"/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:{code:n,redirectUri:a}})),e=await e,t(),e);localStorage.setItem("jwt",r),l.setUsername(d),[e,t]=o(()=>i("/preferences")),await e,t()}catch(r){p.show(((c=r==null?void 0:r.data)==null?void 0:c.message)??"Es ist ein interner Fehler aufgetreten: "+r),[e,t]=o(()=>i("/")),await e,t()}}return(s,a)=>(y(),f("div",w,a[0]||(a[0]=[g("p",null,"Authentifiziere dichâ€¦",-1)])))}};export{T as default};
