import{g as m,j as h,T as _,s as o,p as i,c as f,a as g,o as y}from"./DRGyXaEe.js";import{u as w}from"./BmTQe5BE.js";const S={class:"container py-5 text-center"},T={__name:"auth-redirect",async setup(b){var c;let e,t;const u=h(),p=m(),l=w(),n=u.query.code;if(n){const r=_(),a=`${r.public.baseUrl.replace(/\/$/,"")}${r.public.oauth.redirectPath}`;try{const{token:s,username:d}=([e,t]=o(()=>$fetch(r.public.apiBase+"/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:{code:n,redirectUri:a}})),e=await e,t(),e);localStorage.setItem("jwt",s),l.setUsername(d),[e,t]=o(()=>i("/preferences")),await e,t()}catch(s){p.show(((c=s==null?void 0:s.data)==null?void 0:c.message)??"Es ist ein interner Fehler aufgetreten: "+s),[e,t]=o(()=>i("/")),await e,t()}}return(r,a)=>(y(),f("div",S,a[0]||(a[0]=[g("p",null,"Authentifiziere dichâ€¦",-1)])))}};export{T as default};
